//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.Quizzes = new HashSet<Quiz>();
            this.QuizAttempts = new HashSet<QuizAttempts>();
        }
    
        public int ParticipantID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> TimeSpent { get; set; }
        public string Password { get; set; }
        public int QuizId { get; set; }
        public int UserId { get; set; }
    
        protected virtual ICollection<Quiz> Quizzes { get; set; }
        public virtual ICollection<QuizAttempts> QuizAttempts { get; set; }
    }
}
