//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizAttempts
    {
        public QuizAttempts()
        {
            this.Participants = new HashSet<Participant>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int QuizId { get; set; }
    
        protected virtual ICollection<Participant> Participants { get; set; }
        protected virtual Quiz Quiz { get; set; }
    }
}
