//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Quizzes = new HashSet<Quiz>();
        }
    
        public int Id { get; set; }
        public string TopicName { get; set; }
        public string Subject { get; set; }
        public int AdminUserId { get; set; }
    
        protected virtual AdminUser CreatedBy { get; set; }
        protected virtual ICollection<Quiz> Quizzes { get; set; }
    }
}
